# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 17:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kalabash_api', '0003_kalabashextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalabashinstance',
            name='alias_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kalabashinstance',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 14, 17, 17, 37, 147971, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kalabashinstance',
            name='domain_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kalabashinstance',
            name='extensions',
            field=models.ManyToManyField(blank=True, to='kalabash_api.KalabashExtension'),
        ),
        migrations.AddField(
            model_name='kalabashinstance',
            name='mailbox_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kalabashinstance',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='kalabashinstance',
            name='last_request',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
