# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-01 14:40
from __future__ import unicode_literals

from django.db import migrations, models


def move_versions(apps, schema_editor):
    """Move versions to new field."""
    KalabashInstance = apps.get_model("kalabash_api", "KalabashInstance")
    for instance in KalabashInstance.objects.all():
        instance.new_known_version = "{}".format(instance.known_version)
        instance.save()
    KalabashExtension = apps.get_model("kalabash_api", "KalabashExtension")
    for extension in KalabashExtension.objects.all():
        extension.new_version = "{}".format(extension.version)
        extension.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('kalabash_api', '0006_auto_20161226_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalabashextension',
            name='new_version',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kalabashinstance',
            name='new_known_version',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.RunPython(move_versions, backwards),
        migrations.RemoveField(
            model_name='kalabashextension',
            name='version',
        ),
        migrations.RemoveField(
            model_name='kalabashinstance',
            name='known_version',
        ),
    ]
